// src/services/mockDesigns.js
// -----------------------------------------------------------------------------
// Curated Pinterest-style architectural building designs catalog tailored for
// diverse residential and mixed-use developments in Bangladesh (2 to 14+ stories).
// Includes spatial unit layouts (Rooms, Bathrooms, Balconies, Dining & Living).
// -----------------------------------------------------------------------------

export const MOCK_DESIGNS = [
  {
    id: 1,
    title: "Gulshan Modernist Horizon",
    floors: 10,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 5.0,
    built_area_sqft: 22500,
    units_per_floor: 2,
    unit_size_sqft: 1950,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 4,
    dining_space: "16' × 14' Executive Formal Dining with Natural Light Court & Handwash Alcove",
    drawing_space: "20' × 16' Grand Family Living & Formal Drawing Hall with South Balcony",
    kitchen_space: "12' × 9' Modular Island Kitchen with Gas Exhaust & Utility Terrace",
    parking_capacity: 12,
    architectural_style: "Biophilic Contemporary",
    image_url:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.85,
    description:
      "A 10-story biophilic luxury residential tower with multi-tiered cantilevered balconies, integrated planter boxes, full basement parking, and a lush community rooftop garden.",
    features: [
      "Lush Rooftop Garden",
      "Full Basement Parking",
      "Double-glazed Energy Facade",
      "Cross-Ventilated Units",
      "Dedicated EV Charging",
    ],
  },
  {
    id: 2,
    title: "Dhanmondi Brick & Glass Villa",
    floors: 5,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 4.0,
    built_area_sqft: 9800,
    units_per_floor: 1,
    unit_size_sqft: 1960,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 3,
    dining_space: "18' × 13' Spacious Open Dining with Timber Louver Partition & Garden View",
    drawing_space: "22' × 16' Full-Span Drawing Lounge with Terracotta Brick Accent Wall",
    kitchen_space: "14' × 10' Gourmet Kitchen with Breakfast Bar & Maid's Toilet Corner",
    parking_capacity: 5,
    architectural_style: "Exposed Brick & Louver",
    image_url:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.15,
    description:
      "Contemporary 5-story single-unit luxury residence inspired by tropical modernism. Features exposed red terracotta brickwork, adjustable timber louvers, and private garden terraces.",
    features: [
      "Exposed Terracotta Brick",
      "Ground Floor Covered Garage",
      "Single Unit Privacy",
      "Rainwater Harvesting",
      "Green Rooftop Lounge",
    ],
  },
  {
    id: 3,
    title: "Uttara Urban Apex Tower",
    floors: 8,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Helipad",
    min_katha: 5.5,
    built_area_sqft: 24500,
    units_per_floor: 2,
    unit_size_sqft: 1530,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 3,
    dining_space: "14' × 12' Dedicated Central Dining Space with Integrated Crockery Unit",
    drawing_space: "17' × 14' Contemporary Living Room with Wide Window Glazing",
    kitchen_space: "11' × 8' Ergonomic Parallel Kitchen with Dry Balcony",
    parking_capacity: 14,
    architectural_style: "High-Tech Minimalist",
    image_url:
      "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.78,
    description:
      "Modern 8-story commercial & residential hybrid tower engineered with structural steel accents, subterranean dual-level parking, emergency rooftop helipad, and sky lounge.",
    features: [
      "Certified Rooftop Helipad",
      "Subterranean 2-Level Basement",
      "Central Smart Security Hub",
      "Curtain Glass Facade",
      "RAJUK Code Optimized",
    ],
  },
  {
    id: 4,
    title: "Banani Boutique Enclave",
    floors: 4,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 3.5,
    built_area_sqft: 6800,
    units_per_floor: 1,
    unit_size_sqft: 1700,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    dining_space: "15' × 12' Scandinavian Minimalist Dining Area adjacent to Open Kitchen",
    drawing_space: "19' × 15' Airy Drawing Room connected to Front Veranda",
    kitchen_space: "12' × 8' Open-Concept Kitchen with Quartz Countertop",
    parking_capacity: 3,
    architectural_style: "Scandinavian Minimalist",
    image_url:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.0,
    description:
      "Smart 4-story boutique residential building designed for compact 3.5 Katha plots. Maximizes floor area ratio (FAR) with expansive open terrace and ground floor car parking.",
    features: [
      "Expansive Open Sky Terrace",
      "Compact 3.5 Katha Footprint",
      "Ground Level Stilt Parking",
      "Natural Daylighting Shafts",
      "Acoustic Insulation",
    ],
  },
  {
    id: 5,
    title: "Bashundhara Signature Heights",
    floors: 12,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 6.0,
    built_area_sqft: 29000,
    units_per_floor: 2,
    unit_size_sqft: 1200,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 3,
    dining_space: "13' × 11' Well-Ventilated Dining Hall with Dedicated Wash Basin",
    drawing_space: "16' × 13' Family Lounge & Drawing Space with Planter Box Balcony",
    kitchen_space: "10' × 8' L-Shaped Efficient Kitchen with Kitchen Balcony",
    parking_capacity: 16,
    architectural_style: "Modern Tropical",
    image_url:
      "https://images.unsplash.com/photo-1515263487990-61b07816b324?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.9,
    description:
      "12-story eco-conscious apartment complex with cascading vertical gardens, underground parking, solar array canopy, and panoramic community rooftop deck.",
    features: [
      "Vertical Green Living Walls",
      "Solar Panel Canopy Roof",
      "Basement Driver Waiting Lounge",
      "Thermal Break Glass Windows",
      "High Efficiency Elevators",
    ],
  },
  {
    id: 6,
    title: "Mirpur Minimalist Habitat",
    floors: 6,
    has_basement: false,
    has_garage: false,
    rooftop_type: "Open Terrace",
    min_katha: 3.0,
    built_area_sqft: 8100,
    units_per_floor: 2,
    unit_size_sqft: 675,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 2,
    dining_space: "11' × 10' Compact Combined Dining Corner with Kitchen Pass-Through",
    drawing_space: "13' × 11' Cost-Optimized Family Living Room",
    kitchen_space: "8' × 6' Functional Compact Kitchen with Ventilation Window",
    parking_capacity: 0,
    architectural_style: "Cost-Effective Urban",
    image_url:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.1,
    description:
      "Standard 6-story multi-family housing structure engineered for narrow 3 Katha plots. Maximizes interior livable space with open-air community terrace.",
    features: [
      "Optimized for 3 Katha Narrow Plots",
      "Low Construction Cost per Sqft",
      "Open Air Rooftop Clothes Drying & Terrace",
      "Cross Air Flow Bedrooms",
      "Standard Municipal Approval Ready",
    ],
  },
  {
    id: 7,
    title: "Purbachal Green Oasis Triplex",
    floors: 3,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 4.5,
    built_area_sqft: 6800,
    units_per_floor: 1,
    unit_size_sqft: 2260,
    bedrooms: 5,
    bathrooms: 5,
    balconies: 4,
    dining_space: "20' × 15' Banquet-Style Grand Dining Hall with Poolside Deck View",
    drawing_space: "24' × 18' Double-Height Ceiling Formal Drawing Room",
    kitchen_space: "16' × 11' Chef Kitchen with Walk-in Pantry & Wet Kitchen Annex",
    parking_capacity: 3,
    architectural_style: "Resort-Style Luxury",
    image_url:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.82,
    description:
      "Luxurious 3-story residential manor featuring private triplex living, semi-basement garage, perimeter landscape gardens, and an infinity water-feature rooftop.",
    features: [
      "Rooftop Hydroponic Garden",
      "Semi-Basement Parking Garage",
      "Internal Light Court & Skylight",
      "Private Elevators",
      "Earthquake Resistant Frame",
    ],
  },
  {
    id: 8,
    title: "Chittagong Hillside Grand View",
    floors: 7,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 4.5,
    built_area_sqft: 17500,
    units_per_floor: 2,
    unit_size_sqft: 1250,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 3,
    dining_space: "14' × 12' Scenic Dining Space with Panoramic Hill/Bay Window",
    drawing_space: "17' × 14' Breezy Front Living Lounge with Deep Shaded Veranda",
    kitchen_space: "11' × 8' Heavy-Duty Kitchen with Service Veranda",
    parking_capacity: 8,
    architectural_style: "Terraced Modern",
    image_url:
      "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.95,
    description:
      "7-story terraced structure engineered for sloped and standard urban terrain under CDA guidelines. Features deep verandas, reinforced retaining foundation, and open terrace.",
    features: [
      "CDA Guideline Optimized",
      "Dual-Level Retaining Basement",
      "Panoramic Bay View Verandas",
      "High Wind Load Structural Resistance",
      "Open Stargazing Terrace",
    ],
  },
  {
    id: 9,
    title: "Lalmatia Sunlit Studios",
    floors: 5,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 3.0,
    built_area_sqft: 7200,
    units_per_floor: 2,
    unit_size_sqft: 720,
    bedrooms: 2,
    bathrooms: 2,
    balconies: 2,
    dining_space: "12' × 10' Sun-Drenched Dining Nook next to South Balcony",
    drawing_space: "14' × 12' Bright Drawing Lounge with Cross-Air Circulation",
    kitchen_space: "9' × 7' Modern Modular Kitchenette with Washing Station",
    parking_capacity: 3,
    architectural_style: "Contemporary Mid-Rise",
    image_url:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.05,
    description:
      "Compact and sun-drenched 5-story building featuring ground floor vehicle bay, recessed balconies for monsoon shading, and rooftop potted garden.",
    features: [
      "Monsoon-Shielded Recessed Balconies",
      "Compact 3 Katha Plot Fit",
      "Ground Level Car Stalls",
      "Community Rooftop Herbal Garden",
      "South-Facing Solar Exposure",
    ],
  },
  {
    id: 10,
    title: "Baridhara Diplomatic Zenith",
    floors: 14,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Helipad",
    min_katha: 7.0,
    built_area_sqft: 42000,
    units_per_floor: 2,
    unit_size_sqft: 1500,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 4,
    dining_space: "18' × 14' Ultra-Luxury Formal Dining Hall with Private Butler Pantry",
    drawing_space: "22' × 18' Diplomatic State Drawing Room with Soundproof Glass",
    kitchen_space: "15' × 10' High-End Italian Modular Kitchen with Prep Island",
    parking_capacity: 22,
    architectural_style: "Ultra-Luxury International",
    image_url:
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.8,
    description:
      "Prestigious 14-story ultra-luxury condominium featuring reinforced structural core, underground double basement, certified rooftop helipad, and private lift lobbies.",
    features: [
      "Executive Rooftop Helipad",
      "Reinforced Double Basement",
      "Dedicated Private Lift Lobbies",
      "Soundproof Quadruple Glazing",
      "Full Automation & Security Core",
    ],
  },
  {
    id: 11,
    title: "Rajshahi Silk City Heights",
    floors: 9,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 4.5,
    built_area_sqft: 19500,
    units_per_floor: 3,
    unit_size_sqft: 720,
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    dining_space: "12' × 11' Central Cooling Dining Space with Thermal Cavity Insulation",
    drawing_space: "15' × 12' Family Living Room with North-Facing Balcony",
    kitchen_space: "9' × 7' Heat-Mitigated Kitchen with Exhaust Shaft",
    parking_capacity: 9,
    architectural_style: "Thermal-Optimized Modern",
    image_url:
      "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.1,
    description:
      "9-story residential complex specially engineered with hollow-brick exterior insulation, ground floor open garage, and rooftop terrace for northern heat mitigation.",
    features: [
      "RDA Rule Compliant",
      "Thermal Insulation Cavity Walls",
      "Ground Floor Open Car Bay",
      "Spacious Open Rooftop",
      "3-Unit Cost Efficient Layout",
    ],
  },
  {
    id: 12,
    title: "Khulna Waterfront Vista",
    floors: 6,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 4.0,
    built_area_sqft: 11200,
    units_per_floor: 2,
    unit_size_sqft: 930,
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    dining_space: "13' × 11' River Breeze Dining Space with Sliding Glass Door",
    drawing_space: "16' × 13' Waterfront Facing Drawing Room with Shaded Veranda",
    kitchen_space: "10' × 8' Anti-Corrosion Tiled Kitchen with Utility Balcony",
    parking_capacity: 5,
    architectural_style: "Coastal Modern",
    image_url:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.95,
    description:
      "6-story coastal-resilient residential apartment with corrosion-resistant finishes, cantilevered shaded decks, ground garage, and breezy open rooftop terrace.",
    features: [
      "KDA Compliance Standard",
      "Salinity Resistant Concrete Mix",
      "Ground Level Covered Parking",
      "Open River Breeze Terrace",
      "Dual Master Bed Floorplans",
    ],
  },
  {
    id: 13,
    title: "Sylhet Tea-Estate Modern Duplex",
    floors: 2,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 3.5,
    built_area_sqft: 4200,
    units_per_floor: 1,
    unit_size_sqft: 2100,
    bedrooms: 4,
    bathrooms: 4,
    balconies: 3,
    dining_space: "18' × 14' Ground Floor Family Dining Hall with Veranda Access",
    drawing_space: "22' × 16' Expansive Living Lounge with Fireplace / Garden View",
    kitchen_space: "14' × 10' Modern Kitchen with Walk-in Store Room",
    parking_capacity: 2,
    architectural_style: "Contemporary Tropical Duplex",
    image_url:
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.1,
    description:
      "Serene 2-story luxury private duplex villa with pitched rooflines, private garden porch, garage, and panoramic open terrace overlooking scenic surroundings.",
    features: [
      "Single-Family 2-Story Duplex",
      "Ground Floor Private Lawn",
      "Covered 2-Car Garage",
      "Rainwater Runoff Gutter System",
      "High Ceiling Living Lounge",
    ],
  },
  {
    id: 14,
    title: "Uttara Sector 3 Family Residence",
    floors: 7,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 4.0,
    built_area_sqft: 14000,
    units_per_floor: 2,
    unit_size_sqft: 1000,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 3,
    dining_space: "13' × 12' Family Dining Space with Wash Basin Cabinet",
    drawing_space: "16' × 13' Formal Drawing Room with Separate Family Living Zone",
    kitchen_space: "10' × 8' Well-Ventilated Kitchen with Attached Balcony",
    parking_capacity: 7,
    architectural_style: "Modern Urban Residential",
    image_url:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.95,
    description:
      "Elegant 7-story family apartment building designed for standard 4 Katha plots in Sector 3. Includes dedicated ground floor parking bays and landscaped rooftop garden.",
    features: [
      "Popular 7-Story Dhaka Layout",
      "Ground Floor Covered Stilt Garage",
      "Community Rooftop Garden",
      "Dual Balconies per Unit",
      "RAJUK Master Plan Approved",
    ],
  },
  {
    id: 15,
    title: "Motijheel Commercial & Living Tower",
    floors: 11,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 6.0,
    built_area_sqft: 32000,
    units_per_floor: 3,
    unit_size_sqft: 970,
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    dining_space: "13' × 11' Urban Compact Dining with Breakfast Counter",
    drawing_space: "15' × 13' Sound-Insulated Drawing Room",
    kitchen_space: "10' × 7' Functional Linear Kitchen with Utility Corner",
    parking_capacity: 15,
    architectural_style: "Commercial-Residential Hybrid",
    image_url:
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.88,
    description:
      "Dynamic 11-story mixed-use tower with retail ground floor, 2 office floors, 8 residential floors, basement parking, and breezy open terrace.",
    features: [
      "11-Story Mixed-Use Design",
      "Underground Basement Parking",
      "High Speed Twin Elevators",
      "Fire Suppression Sprinkler Network",
      "Wide Central Staircase",
    ],
  },
  {
    id: 16,
    title: "Bashundhara Smart Eco-Living",
    floors: 8,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 5.0,
    built_area_sqft: 19800,
    units_per_floor: 2,
    unit_size_sqft: 1235,
    bedrooms: 3,
    bathrooms: 3,
    balconies: 3,
    dining_space: "14' × 12' Smart Dining Area with Ambient LED Lighting & Planter Divider",
    drawing_space: "17' × 14' Eco-Smart Drawing Hall with Automated Climate Louvers",
    kitchen_space: "11' × 9' Smart Sensor Kitchen with Composting Waste Chute",
    parking_capacity: 10,
    architectural_style: "Smart Sustainable",
    image_url:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.92,
    description:
      "8-story smart sustainable residential residence equipped with rooftop hydroponics, basement parking, solar backup, and thermal-break glass facades.",
    features: [
      "8-Story Medium High-Rise",
      "Solar Power Integration",
      "Full Basement Garage",
      "Rooftop Community Pavilion",
      "IoT Smart Lighting System",
    ],
  },
];
