// src/services/mockDesigns.js
// -----------------------------------------------------------------------------
// Curated Pinterest-style architectural building designs catalog tailored for
// 5 to 10-story residential and mixed-use developments in Bangladesh.
// Matches the MySQL database schema and includes rich spatial metadata.
// -----------------------------------------------------------------------------

export const MOCK_DESIGNS = [
  {
    id: 1,
    title: "Gulshan Modernist Horizon",
    floors: 10,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 5.0,
    built_area_sqft: 22500,
    units_per_floor: 2,
    parking_capacity: 12,
    architectural_style: "Biophilic Contemporary",
    image_url:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.85,
    description:
      "A 10-story biophilic luxury residential tower with multi-tiered cantilevered balconies, integrated planter boxes, full basement parking, and a lush community rooftop garden.",
    features: [
      "Lush Rooftop Garden",
      "Full Basement Parking",
      "Double-glazed Energy Facade",
      "Cross-Ventilated Units",
      "Dedicated EV Charging",
    ],
  },
  {
    id: 2,
    title: "Dhanmondi Brick & Glass Villa",
    floors: 5,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 4.0,
    built_area_sqft: 9800,
    units_per_floor: 1,
    parking_capacity: 5,
    architectural_style: "Exposed Brick & Louver",
    image_url:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.15,
    description:
      "Contemporary 5-story single-unit luxury residence inspired by tropical modernism. Features exposed red terracotta brickwork, adjustable timber louvers, and private garden terraces.",
    features: [
      "Exposed Terracotta Brick",
      "Ground Floor Covered Garage",
      "Single Unit Privacy",
      "Rainwater Harvesting",
      "Green Rooftop Lounge",
    ],
  },
  {
    id: 3,
    title: "Uttara Urban Apex Tower",
    floors: 10,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Helipad",
    min_katha: 6.5,
    built_area_sqft: 31000,
    units_per_floor: 3,
    parking_capacity: 18,
    architectural_style: "High-Tech Minimalist",
    image_url:
      "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.78,
    description:
      "High-density 10-story commercial & residential hybrid tower engineered with structural steel accents, subterranean dual-level parking, emergency rooftop helipad, and sky lounge.",
    features: [
      "Certified Rooftop Helipad",
      "Subterranean 2-Level Basement",
      "Central Smart Security Hub",
      "Curtain Glass Facade",
      "RAJUK Code Optimized",
    ],
  },
  {
    id: 4,
    title: "Banani Boutique Enclave",
    floors: 5,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 3.5,
    built_area_sqft: 8200,
    units_per_floor: 1,
    parking_capacity: 4,
    architectural_style: "Scandinavian Minimalist",
    image_url:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.0,
    description:
      "Smart 5-story boutique residential building designed for compact 3.5 Katha plots. Maximizes floor area ratio (FAR) with expansive open terrace and ground floor car parking.",
    features: [
      "Expansive Open Sky Terrace",
      "Compact 3.5 Katha Footprint",
      "Ground Level Stilt Parking",
      "Natural Daylighting Shafts",
      "Acoustic Insulation",
    ],
  },
  {
    id: 5,
    title: "Bashundhara Signature Heights",
    floors: 10,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 5.0,
    built_area_sqft: 24000,
    units_per_floor: 2,
    parking_capacity: 14,
    architectural_style: "Modern Tropical",
    image_url:
      "https://images.unsplash.com/photo-1515263487990-61b07816b324?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.9,
    description:
      "10-story eco-conscious apartment complex with cascading vertical gardens, underground parking, solar array canopy, and panoramic community rooftop deck.",
    features: [
      "Vertical Green Living Walls",
      "Solar Panel Canopy Roof",
      "Basement Driver Waiting Lounge",
      "Thermal Break Glass Windows",
      "High Efficiency Elevators",
    ],
  },
  {
    id: 6,
    title: "Mirpur Minimalist Habitat",
    floors: 5,
    has_basement: false,
    has_garage: false,
    rooftop_type: "Open Terrace",
    min_katha: 3.0,
    built_area_sqft: 6700,
    units_per_floor: 2,
    parking_capacity: 0,
    architectural_style: "Cost-Effective Urban",
    image_url:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.1,
    description:
      "Budget-optimized 5-story multi-family housing structure engineered for narrow 3 Katha plots. Maximizes interior livable space with open-air community terrace.",
    features: [
      "Optimized for 3 Katha Narrow Plots",
      "Low Construction Cost per Sqft",
      "Open Air Rooftop Clothes Drying & Terrace",
      "Cross Air Flow Bedrooms",
      "Standard Municipal Approval Ready",
    ],
  },
  {
    id: 7,
    title: "Purbachal Green Oasis Duplex",
    floors: 5,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 4.5,
    built_area_sqft: 11200,
    units_per_floor: 1,
    parking_capacity: 6,
    architectural_style: "Resort-Style Luxury",
    image_url:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.82,
    description:
      "Luxurious 5-story residential manor featuring private duplex units, semi-basement garage, perimeter landscape gardens, and an infinity water-feature rooftop.",
    features: [
      "Rooftop Hydroponic Garden",
      "Semi-Basement Parking Garage",
      "Internal Light Court & Skylight",
      "Private Elevators",
      "Earthquake Resistant Frame",
    ],
  },
  {
    id: 8,
    title: "Chittagong Hillside Grand View",
    floors: 10,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 5.5,
    built_area_sqft: 26000,
    units_per_floor: 2,
    parking_capacity: 15,
    architectural_style: "Terraced Modern",
    image_url:
      "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.95,
    description:
      "10-story terraced structure engineered for sloped and standard urban terrain under CDA guidelines. Features deep verandas, reinforced retaining foundation, and open terrace.",
    features: [
      "CDA Guideline Optimized",
      "Dual-Level Retaining Basement",
      "Panoramic Bay View Verandas",
      "High Wind Load Structural Resistance",
      "Open Stargazing Terrace",
    ],
  },
  {
    id: 9,
    title: "Lalmatia Sunlit Studios",
    floors: 5,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Garden",
    min_katha: 3.0,
    built_area_sqft: 7200,
    units_per_floor: 2,
    parking_capacity: 3,
    architectural_style: "Contemporary Mid-Rise",
    image_url:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.05,
    description:
      "Compact and sun-drenched 5-story building featuring ground floor vehicle bay, recessed balconies for monsoon shading, and rooftop potted garden.",
    features: [
      "Monsoon-Shielded Recessed Balconies",
      "Compact 3 Katha Plot Fit",
      "Ground Level Car Stalls",
      "Community Rooftop Herbal Garden",
      "South-Facing Solar Exposure",
    ],
  },
  {
    id: 10,
    title: "Baridhara Diplomatic Zenith",
    floors: 10,
    has_basement: true,
    has_garage: true,
    rooftop_type: "Helipad",
    min_katha: 7.0,
    built_area_sqft: 34000,
    units_per_floor: 2,
    parking_capacity: 20,
    architectural_style: "Ultra-Luxury International",
    image_url:
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.8,
    description:
      "Prestigious 10-story ultra-luxury condominium featuring reinforced structural core, underground double basement, certified rooftop helipad, and private lift lobbies.",
    features: [
      "Executive Rooftop Helipad",
      "Reinforced Double Basement",
      "Dedicated Private Lift Lobbies",
      "Soundproof Quadruple Glazing",
      "Full Automation & Security Core",
    ],
  },
  {
    id: 11,
    title: "Rajshahi Silk City Heights",
    floors: 10,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 4.5,
    built_area_sqft: 21000,
    units_per_floor: 3,
    parking_capacity: 10,
    architectural_style: "Thermal-Optimized Modern",
    image_url:
      "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 1.1,
    description:
      "10-story residential complex specially engineered with hollow-brick exterior insulation, ground floor open garage, and rooftop terrace for northern heat mitigation.",
    features: [
      "RDA Rule Compliant",
      "Thermal Insulation Cavity Walls",
      "Ground Floor Open Car Bay",
      "Spacious Open Rooftop",
      "3-Unit Cost Efficient Layout",
    ],
  },
  {
    id: 12,
    title: "Khulna Waterfront Vista",
    floors: 5,
    has_basement: false,
    has_garage: true,
    rooftop_type: "Open Terrace",
    min_katha: 4.0,
    built_area_sqft: 9200,
    units_per_floor: 2,
    parking_capacity: 4,
    architectural_style: "Coastal Modern",
    image_url:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    aspect_ratio: 0.95,
    description:
      "5-story coastal-resilient residential apartment with corrosion-resistant finishes, cantilevered shaded decks, ground garage, and breezy open rooftop terrace.",
    features: [
      "KDA Compliance Standard",
      "Salinity Resistant Concrete Mix",
      "Ground Level Covered Parking",
      "Open River Breeze Terrace",
      "Dual Master Bed Floorplans",
    ],
  },
];
